# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano_v2
    shield: borg_left
  - board: nice_nano_v2
    shield: borg_right
    snippet: zmk-usb-logging
    snippet: studio-rpc-usb-uart

# Settings Reset firmware
# This will build a firmware that can wipe all settings from your
# controller. It's useful when you have bluetooth issues or when your split
# keyboard halfs are not pairing.
#
# More info:
# https://zmk.dev/docs/troubleshooting#split-keyboard-halves-unable-to-pair
  - board: nice_nano_v2
    shield: settings_reset
